---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present

- name: Install Docker SDK for Python
  pip:
    name: docker
    executable: pip3

- name: Pull Jenkins Docker image
  docker_image:
    name: jenkins/jenkins:lts
    source: pull

- name: Run Jenkins container
  docker_container:
    name: jenkins
    image: jenkins/jenkins:lts
    state: started
    restart_policy: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

- name: Create a volume for Jenkins data
  docker_volume:
    name: jenkins_home