apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-container
  template:
    metadata:
      labels:
        app: python-container
    spec:
      containers:
      - name: python-container
        image: 539247483379.dkr.ecr.us-east-1.amazonaws.com/python/depi_project:latest # ecr repo here
