---
# roles/docker/tasks/main.yml
- name: Update apt package index
  apt:
    update_cache: yes

- name: Install required packages for Docker
  apt:
    name:
      - ca-certificates
      - curl
      - lsb-release
    state: present

- name: Create Docker GPG key directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  args:
    creates: /etc/apt/keyrings/docker.asc  # Only run if the file doesn't exist
  register: curl_result

- name: Set permissions on Docker GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'
  when: curl_result.changed  # Run this only if the download command changed the state

- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present

- name: Update apt package index after adding Docker repo
  apt:
    update_cache: yes

- name: Update Apt package index
  ansible.builtin.apt:
    update_cache: yes


- name: Install Docker and its components
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Create Docker network for Jenkins
  docker_network:
    name: jenkins
    state: present